version: '3.2'

services:
  nginx:
    restart: always
    image: nginx:1.22.1-alpine
    container_name: nginx
    ports:
      - 10008:80
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
